### ISSUE TITLE
Где его искать?

### ISSUE THREAD

**Issue by Maelow** [olehpratsko/Yandex.Market-oc-extension#2]
После копирования, не произошло ровным счетом ничего, необходимо где-то включить или что-то еще настроить?

**Comment by olehpratsko** [comment]
Установка стандартная. Возможно плагин не совместим с версией движка.

**Comment by olehpratsko** [comment]
Если ссылка не работает, скорее всего проблема в несовместимости.
`адрес_вашего_сайта/index.php?route=extension/feed/yandex_market`
